name: "Monorepo setup"
description: "Setup pnpm and caches"
inputs:
  cache-key:
    description: "Key to cache"
    required: false
    default: "full"
runs:
  using: composite
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18

    - uses: pnpm/action-setup@v4.0.0
      with:
        version: 8.15.3

    - name: Set pnpm store path
      shell: bash
      run: echo "PNPM_STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ${{ env.PNPM_STORE_PATH }}
        key: pnpm7-${{ runner.os }}-${{ inputs.cache-key }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          pnpm7-${{ runner.os }}-${{ inputs.cache-key }}-
          pnpm7-${{ runner.os }}-

    - name: Cache turborepo
      uses: actions/cache@v2
      with:
        path: node_modules/.cache/turbo/
        key: turbo2-${{ runner.os }}-${{ inputs.cache-key }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          turbo2-${{ runner.os }}-${{ inputs.cache-key }}-
          turbo2-${{ runner.os }}-

    - name: Cache playwright browsers
      uses: actions/cache@v2
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          playwright-${{ runner.os }}-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --filter @findkit/root --filter @findkit/ui --filter @findkit/fetch

    - name: Build all
      shell: bash
      run: |
        set -eu
        ./node_modules/.bin/turbo run build --filter @findkit/ui
