## Unique id of the project
id = "docs-findkit-com"

## Human readable name and description of the project
name = "docs.findkit.com"
description = "Findkit Developer Documentation site"

## Crawl schedules. Comment out to disable scheduled crawls.
#full_crawl_schedule = "weekly"

## Target websites to crawl
[[targets]]
host = "docs.findkit.com"

## Docusaurus has no sitemaps so we must walk the site manually
use_sitemap = false
walk_links = true

## CSS selectors to extract the text content from
content_selector = ".markdown"



## Not public yet, so ignore robots rules
respect_robots_meta = false
respect_robots = false