# EU North project
id = "p68GxRvaA" # prod
# id = "ppVD7VPvr:eu-north-1" # dev

## Human readable name and description of the project
name = "findkit.com and docs.findkit.com"

description = "Deploy US version with findkit deploy -P pP9OykWDd:us-west-1"

## Crawl schedules. Comment out to disable scheduled crawls.
#full_crawl_schedule = "weekly"

# Target websites to crawl
[[targets]]
host = "docs.findkit.com"
workers = ["worker.js"]

# Docusaurus has no sitemaps so we must walk the site manually
use_sitemap = false
walk_links = true

## CSS selectors to extract the text content from
content_selector = ".markdown"
cleanup_selector = ".theme-code-block"

# Docusaurus adds "| Findkit" to the title so want to grab the text before that
title_selector_regex = '([^\|]+)'

deny_patterns = ["/ui-api/", "/ui-examples/"]

[[targets.tags]]
pathname_regex = '^\/([^\\/]+)'
on_match = "$1"

[[targets.tags]]
pathname_regex = '^\/[^\/]+$'
on_match = "root"


[[targets]]
host = "www.findkit.com"

use_sitemap = true
walk_links = false
