// This file is auto-generated with postcss-ts-classnames.

type ClassNames =
  | "findkit--back-link"
  | "findkit--close-button"
  | "findkit--content"
  | "findkit--cross"
  | "findkit--error-container"
  | "findkit--error-message"
  | "findkit--error-title"
  | "findkit--group"
  | "findkit--group-title"
  | "findkit--header"
  | "findkit--header-hidden"
  | "findkit--highlight"
  | "findkit--hit"
  | "findkit--hit-title"
  | "findkit--hit-title-link"
  | "findkit--hit-url"
  | "findkit--load-more-button"
  | "findkit--logo"
  | "findkit--logo-animating"
  | "findkit--modal"
  | "findkit--modal-visible"
  | "findkit--more-link"
  | "findkit--plain"
  | "findkit--retry-button"
  | "findkit--search-input"
  | "findkit--search-input-wrap";