#!/bin/sh

set -eu

if [ "${1:-}" = "" ]; then
    echo "usage: update-all-imports <@findkit/ui@version>"
    echo "example: update-all-imports 0.5.0"
    exit 1
fi

# Ex. turn @findkit/ui@0.0.1-dev.bdfdd29b0e to 0.0.1-dev.bdfdd29b0e
version="$(echo $1 | cut -d @ -f 3)"

cd "$(git rev-parse --show-toplevel)"

clean_git=

if [ "$(git status --porcelain)" = "" ]; then
    clean_git=1
fi

# Update imports in docs
./tools/update-import ${version} ./packages/docs/docs/ui/setup.md
./tools/update-import ${version} ./packages/docs/docs/ui/params.md

# In static file examples
git ls-files 'packages/ui-examples/static/*/index.html' | xargs -L 1 ./tools/update-import ${version}

# In bundling examples
for bundled in packages/ui-examples/bundled/*/
do
    cd "$bundled"
    tmp=$(mktemp)
    jq --arg version "$version" '.dependencies["@findkit/ui"] = $version' package.json > "$tmp"
    mv "$tmp" package.json
    cd -
done


# The version shipped with docs
cd packages/docs
pnpm install "@findkit/ui@${version}"
cd -

cd packages/ui-examples
pnpm install "@findkit/ui@${version}"
cd -

if [ "$clean_git" = "1" ]; then
    git add .
    git commit -m "Update ui lib imports to ${version}"
fi
