#!/bin/sh

set -eu

version="0.0.1-dev.501e42623d"

cd "$(git rev-parse --show-toplevel)"

./tools/update-import ${version} ./packages/docs/docs/ui/setup.md

git ls-files 'packages/ui-examples/*/index.html' | xargs -L 1 ./tools/update-import ${version}