#!/bin/sh

set -eu

version="$1"

cd "$(git rev-parse --show-toplevel)"

clean_git=

if [ "$(git status --porcelain)" = "" ]; then
    clean_git=1
fi

./tools/update-import ${version} ./packages/docs/docs/ui/setup.md

git ls-files 'packages/ui-examples/*/index.html' | xargs -L 1 ./tools/update-import ${version}

if [ "$clean_git" = "1" ]; then
    git add .
    git commit -m "Update ui lib imports to ${version}"
fi