name: Bundle Size Check

concurrency:
  group: "bundle-size-${{ github.ref }}"
  cancel-in-progress: true

on:
  push:
    branches: [main]
    paths:
      - "packages/ui/**"
      - ".github/workflows/bundle-size.yml"
  pull_request:
    paths:
      - "packages/ui/**"
      - ".github/workflows/bundle-size.yml"
    types: [ready_for_review, synchronize, opened, reopened]

jobs:
  bundle-size:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup-action

      - name: Check bundle sizes
        run: |
          set -eu

          cd packages/ui
          gzip esm/*.js
          echo 'The bundle sizes are now:' > /tmp/sizes
          echo '```' >> /tmp/sizes

          echo 'ls -lh' >> /tmp/sizes
          ls -lh esm/*.js.gz >> /tmp/sizes

          echo >> /tmp/sizes
          echo 'ls -l' >> /tmp/sizes
          ls -l esm/*.js.gz >> /tmp/sizes

          echo '```' >> /tmp/sizes
          echo 'The `index.js` is the loader code which should be as small as possible.' >> /tmp/sizes
          gunzip esm/*.gz

      - name: Comment bundle sizes on commit
        uses: actions/github-script@v6
        if: ${{ github.event_name != 'pull_request'  }}
        with:
          script: |
            const fs = require('fs');
            const sizes = fs.readFileSync('/tmp/sizes', 'utf8');
            await github.rest.repos.createCommitComment({
              commit_sha: context.sha,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: sizes
            })

      - name: Comment bundle sizes on PR
        uses: actions/github-script@v6
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft == false }}
        with:
          script: |
            const fs = require('fs');
            const sizes = fs.readFileSync('/tmp/sizes', 'utf8');
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: sizes
            });

      - name: Print loader file
        run: |
          set -eu

          cd packages/ui
          # esm is in prettier ignore
          cp esm/index.js /tmp/index.js
          ./node_modules/.bin/prettier /tmp/index.js

      - name: Check bundle sizes
        run: cd packages/ui && pnpm run size-limit
