name: Deploy docs.findkit.com

concurrency:
  group: "deploy-docs"

on:
  push:
    branches: [main]
    paths:
      - "packages/docs/**"
      - "packages/ui/**"
      - "packages/ui-examples/**"
      - ".github/workflows/deploy-docs.yml"
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.full_name == 'findkit/findkit' }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - uses: valu-digital/slack-action@master
        with:
          token: ${{ secrets.SLACK_ACCESS_TOKEN }}
          channel: "${{ secrets.SLACK_CHANNEL }}"

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.9.5

      - name: Set pnpm store path
        run: echo "PNPM_STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ${{ env.PNPM_STORE_PATH }}
          key: pnpm-docs-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-docs-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache turborepo
        uses: actions/cache@v2
        with:
          path: node_modules/.cache/turbo/
          key: turbo-docs
          restore-keys: |
            turbo-docs

      - name: Build api docs
        run: |
          set -eu
          # Build ui deps but the the ui itself because we don't need the full
          # build for docs build
          ./node_modules/.bin/turbo run build --filter @findkit/ui^...

          # Build the actual docs from ts types
          ./node_modules/.bin/turbo run build-ui-api-docs --filter @findkit/ui

      - name: Build docusaurus
        run: ./node_modules/.bin/turbo run build --filter @findkit/docs

      - name: Build ui-examples
        run: ./node_modules/.bin/turbo run build-ui-examples --filter @findkit/ui-examples

      - name: Deploy site
        run: |
          set -eu
          mv packages/ui/api-docs-html/api packages/docs/build/ui-api

          mkdir -p packages/docs/build/ui-examples
          cp -r packages/ui-examples/static packages/docs/build/ui-examples/static
          cp -r packages/ui-examples/bundled-dist packages/docs/build/ui-examples/bundled

          cd packages/docs && pnpm run deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Start Findkit Crawl
        run: |
          set -eu
          curl --fail-with-body --data '{"mode": "full"}' -H 'content-type: application/json' -H "Authorization: Bearer $FINDKIT_API_KEY"  https://api.findkit.com/v1/projects/p68GxRvaA/crawls
        env:
          FINDKIT_API_KEY: ${{ secrets.FINDKIT_API_KEY }}

      - name: Notify build fail
        if: failure()
        run: |
          set -eu
          slack-message '<!channel> Failed to build https://docs.findkit.com/'
