name: Deploy docs.findkit.com

concurrency:
  group: "deploy-docs"

on:
  push:
    branches: [main]
    paths:
      - "packages/docs/**"
      - "packages/ui/**"
      - ".github/workflows/deploy-docs.yml"
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.9.5

      - name: Set pnpm store path
        run: echo "PNPM_STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ${{ env.PNPM_STORE_PATH }}
          key: pnpm-docs-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-docs-${{ runner.os }}-

      - name: Cache turborepo
        uses: actions/cache@v2
        with:
          path: node_modules/.cache/turbo/
          key: turbo-docs
          restore-keys: |
            turbo-docs

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build api docs
        run: |
          set -eu
          # Build ui deps but the the ui itself because we don't need the full
          # build for docs build
          ./node_modules/.bin/turbo run build --filter @findkit/ui^...

          # Build the actual docs from ts types
          ./node_modules/.bin/turbo run build-ui-api-docs --filter @findkit/ui

      - name: Build docusaurus
        run: ./node_modules/.bin/turbo run build --filter @findkit/docs

      - name: Deploy site
        run: |
          set -eu
          mv packages/ui/api-docs-html/api packages/docs/build/api
          cd packages/docs && pnpm run deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
