name: Publish npm package

concurrency:
  group: "npm-publish"

on:
  push:
    branches:
      - release/*/*

env:
  AWS_EC2_METADATA_DISABLED: true

jobs:
  publish:
    permissions:
      id-token: write # needed to interact with GitHub's OIDC Token endpoint.
      contents: read # read the repo itself
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          # Fetch full history to get all tags so we can get PREV_VERSION
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_WORKFLOW_ROLE_ARN }}
          aws-region: eu-north-1

      - name: Test AWS creds
        run: |
          set -eu
          aws sts get-caller-identity
          aws s3 ls s3://${{ secrets.FINDKIT_CDN_S3 }}

      - name: Publish
        uses: valu-digital/npm-packages/.github/release-action@master
        env:
          FINDKIT_CDN_S3: "${{ secrets.FINDKIT_CDN_S3 }}"
        with:
          slack_access_token: "${{ secrets.SLACK_ACCESS_TOKEN }}"
          slack_channel: "#esa-test"
          npm_token: "${{ secrets.NPM_TOKEN }}"
