name: Test
on:
  push:
    branches: [master]
  pull_request:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.9.0

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Cache playwright browsers
        uses: actions/cache@v2
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build all
        run: ./node_modules/.bin/turbo run build

      - name: Run @findkit/tests
        run: cd packages/fetch && pnpm run test

      - name: Install Playwright Browsers
        run: cd packages/ui && ./node_modules/.bin/playwright install --with-deps

      - name: Run Playwright tests
        run: |
          set -eu
          cd packages/ui
          pnpm run build-test
          pnpm run playwright-test

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: packages/ui/playwright-report/
          retention-days: 30
