name: Test

concurrency:
  group: "test-ui-${{ github.ref }}"
  cancel-in-progress: true

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - "packages/ui/**"
      - "packages/fetch/**"
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.9.5

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Cache playwright browsers
        uses: actions/cache@v2
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --filter @findkit/ui

      - name: Build all
        run: ./node_modules/.bin/turbo run build --filter @findkit/ui

      - name: Run @findkit/tests
        run: cd packages/fetch && pnpm run test

      - name: Install Playwright Browsers
        run: cd packages/ui && ./node_modules/.bin/playwright install --with-deps

      - name: Run Playwright tests
        run: |
          set -eu
          git config user.email "action@github.com"
          git config user.name "${{ github.actor }}"

          cd packages/ui

          # Sanity check
          ./node_modules/.bin/findkit search -t po8GK3G0r valu

          pnpm run build-test

          pnpm run playwright-test
          ## Use this instead to update snapshots on the ci
          #pnpm run playwright-test --update-snapshots ./tests/visual.spec.ts

          if [ "$(git status --porcelain tests)" != "" ]; then
            git add tests
            git commit -m "Update snapshots [skip actions]"
            # Push back to the pr branch
            git push origin "HEAD:$GITHUB_HEAD_REF"
          fi

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: packages/ui/playwright-report/
          retention-days: 30
